/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author developer1
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public Main() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainWindows = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuGenerateSales = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemClient = new javax.swing.JMenuItem();
        menuItemProduct = new javax.swing.JMenuItem();
        menuItemSeller = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemReportSales = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout MainWindowsLayout = new javax.swing.GroupLayout(MainWindows);
        MainWindows.setLayout(MainWindowsLayout);
        MainWindowsLayout.setHorizontalGroup(
            MainWindowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        MainWindowsLayout.setVerticalGroup(
            MainWindowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home.png"))); // NOI18N
        jMenu1.setText("Menu");
        jMenu1.setPreferredSize(new java.awt.Dimension(80, 40));

        jMenuItem1.setText("Ayuda");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        menuGenerateSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shopping-cart.png"))); // NOI18N
        menuGenerateSales.setText("Ventas");

        jMenuItem3.setText("Punto de Venta");
        jMenuItem3.setName("menuGenerateSaleActionPerformed"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuGenerateSales.add(jMenuItem3);

        jMenuBar1.add(menuGenerateSales);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/box.png"))); // NOI18N
        jMenu3.setText("Mantenimiento");

        menuItemClient.setText("Cliente");
        menuItemClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemClient);

        menuItemProduct.setText("Producto");
        menuItemProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProductActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemProduct);

        menuItemSeller.setText("Vendedor");
        menuItemSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSellerActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemSeller);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/report.png"))); // NOI18N
        jMenu4.setText("Reportes");

        menuItemReportSales.setText("Ventas");
        jMenu4.add(menuItemReportSales);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainWindows)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainWindows)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SalesForm salesForm = new SalesForm();
        CenteredWindow(salesForm);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuItemClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientActionPerformed
        ClientForm clientForm = new ClientForm();
        CenteredWindow(clientForm);
    }//GEN-LAST:event_menuItemClientActionPerformed

    private void menuItemProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProductActionPerformed
        ProductForm productForm = new ProductForm();
        CenteredWindow(productForm);
    }//GEN-LAST:event_menuItemProductActionPerformed

    private void menuItemSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSellerActionPerformed
        SellerForm sellerForm = new SellerForm();
        CenteredWindow(sellerForm);
    }//GEN-LAST:event_menuItemSellerActionPerformed

    static void CenteredWindow(JInternalFrame frame) {
        MainWindows.add(frame);
        Dimension dimension = MainWindows.getSize();
        Dimension frameSize = frame.getSize();
        int x = (dimension.width - frameSize.height) / 2;
        int y = (dimension.height - frameSize.width) / 2;
        frame.setLocation(x, y);
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane MainWindows;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuGenerateSales;
    private javax.swing.JMenuItem menuItemClient;
    private javax.swing.JMenuItem menuItemProduct;
    private javax.swing.JMenuItem menuItemReportSales;
    private javax.swing.JMenuItem menuItemSeller;
    // End of variables declaration//GEN-END:variables
}
